"""Assembles final report files: .md and .html."""
from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


def assemble_report(
    ticker: str,
    timestamp: str,
    agent_outputs: dict[str, Any],
    context: dict[str, Any],
    polished_text: str | None = None,
) -> tuple[str, str]:
    from src.reports.template import render_draft
    draft = render_draft(ticker, context, agent_outputs)
    final_md = polished_text if polished_text else draft

    report_dir = Path("reports") / ticker / timestamp
    report_dir.mkdir(parents=True, exist_ok=True)

    md_path = report_dir / "report.md"
    md_path.write_text(final_md)

    html_path = report_dir / "report.html"
    html_path.write_text(_to_html(final_md, ticker, timestamp))

    return str(md_path), str(html_path)


def _to_html(markdown_text: str, ticker: str, timestamp: str) -> str:
    try:
        import markdown as md_lib
        body = md_lib.markdown(markdown_text, extensions=["tables", "fenced_code"])
    except ImportError:
        import re
        body = "<pre>" + markdown_text.replace("<", "&lt;").replace(">", "&gt;") + "</pre>"

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{ticker} Research Report — {timestamp}</title>
<link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
<style>
  body {{ font-family: system-ui, sans-serif; max-width: 900px; margin: 2rem auto; padding: 1rem; }}
  h1 {{ font-size: 1.8rem; font-weight: bold; margin-bottom: 1rem; }}
  h2 {{ font-size: 1.3rem; font-weight: bold; margin: 1.5rem 0 0.5rem; border-bottom: 1px solid #e5e7eb; }}
  h3 {{ font-size: 1.1rem; font-weight: 600; margin: 1rem 0 0.25rem; }}
  table {{ width: 100%; border-collapse: collapse; margin: 1rem 0; }}
  th, td {{ border: 1px solid #d1d5db; padding: 0.5rem; text-align: left; font-size: 0.9rem; }}
  th {{ background: #f3f4f6; }}
  blockquote {{ border-left: 3px solid #9ca3af; padding-left: 1rem; color: #6b7280; margin: 1rem 0; }}
  a {{ color: #2563eb; }}
  code {{ background: #f3f4f6; padding: 0.1rem 0.3rem; border-radius: 3px; font-size: 0.85rem; }}
  .disclaimer {{ background: #fef3c7; border: 1px solid #f59e0b; padding: 0.75rem; border-radius: 6px; margin: 1rem 0; font-size: 0.85rem; }}
</style>
</head>
<body>
<div class="disclaimer">⚠️ Research aid only — not financial advice. Independently verify all claims before any decision.</div>
{body}
<hr style="margin-top:2rem">
<p style="color:#9ca3af;font-size:0.8rem">Generated by VisionAiry2 at {timestamp}. Free-tier data may be incomplete.</p>
</body>
</html>"""
